---
title: "Curated Collections"
---

*Curated Collections* is a project to provide a national platform
for sustainable digital humanities collections. It is a
collaboration between the [Australian
Research Data Commons](https://www.ardc.edu.au) and the [Sydney Informatics Hub](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub.html), a Core Research Facility of [the University of Sydney](https://www.sydney.edu.au), and is part of the [ARDC's HASS and Indigenous Research Data Commons](https://ardc.edu.au/hass-and-indigenous-research-data-commons/).

## eResearch 2025 BOF Session

[Sustainable Digital Humanities Collections](eRes2025_bof.pptx)

Notes from the session will be added to this website soon.

## How to contact us

Join the [project Slack](https://join.slack.com/t/curatedcollections/shared_invite/zt-3g65gd6jo-6FkQItCbAaMh26RMK9zJPA)

You can also email [m.lynch@sydney.edu.au](mailto:m.lynch@sydney.edu.au) or register a collection in the repository.

## Register a collection

You can let us know about your collection by creating an issue
on the Curated Collections GitHub repository:

[Issues](https://github.com/Sydney-Informatics-Hub/CuratedCollections/issues)

If you don't want to use Git, you can let us know about your interest on Slack or via email.
 



